### ISSUE TITLE
Updated watching/tracking icons

### ISSUE THREAD

**Issue by YesThatAllen** [watchmanmonitoring/discourse#17]
based on this thread

https://meta.discourse.org/t/how-to-change-tracking-icons/30568/5

I want to have all the icons as circles with better icons.

Muted's gray & X is fine.
Regular's black empty circle is fine.
Tracking should be a circle with the fa-comment bubble
Watching should be a full circle with an envelope

So far I've got this

```css
.icon.fa.fa-circle.tracking::before {
content: "\f075";
}
.fa.fa-circle.tracking::before {
content: "\f075";
}

.icon.fa.fa-exclamation-circle.watching::before {
content: "\f003";
}
.fa.fa-exclamation-circle.watching::before {
content: "\f003";
}
```

pasted here:  https://community.watchmanmonitoring.com/admin/customize/css_html
and it's good, but the envelope has no circle around it, so it doesn't really flow
